### ISSUE TITLE
problem compiling

### ISSUE THREAD

**Issue by graylion** [matt335672/pam_close_systemd_system_dbus#2]
# make
cc -fPIC -c -g pam_close_systemd_system_dbus.c
pam_close_systemd_system_dbus.c:5:10: fatal error: security/pam_modules.h: No such file or directory
    5 | #include <security/pam_modules.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:17: pam_close_systemd_system_dbus.o] Error 1

**Comment by matt335672** [comment]
```
sudo apt install libpam0g-dev
```

There may be others. If so, add them below. If not, feel free to close this.

**Comment by graylion** [comment]
that solved it, thanks!
